### ISSUE TITLE
Kinjector does not work with Kicad 6

### ISSUE THREAD

**Issue by chrishoage** [devbisme/kinjector#6]
* KinJector version: 1.0
* KiCad version: 6.0.7
* Python version: Python 3.10.5
* Operating System: Arch Linux

### Description

kinjector fails to run due to a change in the pcbnew api 

```
❯ kinjector --help
Traceback (most recent call last):
  File "/home/chris/.local/bin/kinjector", line 5, in <module>
    from kinjector.cli import main
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/__init__.py", line 5, in <module>
    from .kinjector import *
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/kinjector.py", line 666, in <module>
    class Plot(KinJector):
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/kinjector.py", line 717, in Plot
    "default line width": KinJector.GetSet(PPP.GetLineWidth, PPP.SetLineWidth),
AttributeError: type object 'PCB_PLOT_PARAMS' has no attribute 'GetLineWidth'
```

Reading though the pcbnew.py documentation there is no reference to `GetLineWidth`

https://docs.kicad.org/doxygen-python/classpcbnew_1_1PCB__DIMENSION__BASE.html

It appears that it has moved to `PCB_DIMENSION_BASE.GetLineThickness`

### What I Did
Installed though pipx

```
pipx install --system-site-packages https://github.com/devbisme/kinjector/archive/refs/tags/1.0.0.zip
```

```
❯ kinjector --help
Traceback (most recent call last):
  File "/home/chris/.local/bin/kinjector", line 5, in <module>
    from kinjector.cli import main
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/__init__.py", line 5, in <module>
    from .kinjector import *
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/kinjector.py", line 666, in <module>
    class Plot(KinJector):
  File "/home/chris/.local/pipx/venvs/kinjector/lib/python3.10/site-packages/kinjector/kinjector.py", line 717, in Plot
    "default line width": KinJector.GetSet(PPP.GetLineWidth, PPP.SetLineWidth),
AttributeError: type object 'PCB_PLOT_PARAMS' has no attribute 'GetLineWidth'
```

**Comment by devbisme** [comment]
Yes, there are dozens of incompatibilities with the pcbnew.py in KiCad 6. Given the almost non-existent usage of kinjector, upgrading is a low priority.

What specific use did you have for kinjector? Possibly there is a more focused package that will serve your application.

**Comment by chrishoage** [comment]
> Yes, there are dozens of incompatibilities with the pcbnew.py in KiCad 6. Given the almost non-existent usage of kinjector, upgrading is a low priority.

Makes sense, I'd just thought I'd report it anyway :) 

> What specific use did you have for kinjector? Possibly there is a more focused package that will serve your application.

I've been using [ergogen](https://github.com/ergogen/ergogen) to develop a keyboard. This software produces a kicad_pcb file with all the footprints laid out according to the declarative configuration. 

My wish was to be able to do a merge of a kicad_pcb file which contains all of the vias and traces with updated footprint positions. 

There was one other piece of software I looked at called [kicad-to-ergogen](https://github.com/torik42/kicad-to-ergogen) but it wasn't fitting my needs so thought I might try kinjector since it might have let me load the generated kicad_pcb file, load the traced kicad_pcb file, extract the traces and vias, load them into the generated footprints and write them back to the traced kicad_pcb file.

**Comment by devbisme** [comment]
TBH, I don't really understand the design flow you described and it's probably not worth your time to explain it further. However, if what you need is to get the footprint positions from the ergogen-PCB into the traced-PCB, then you could use [my branch of kicad_component_layout](https://github.com/devbisme/kicad_component_layout). This tool could extract the footprint positions from the ergogen-PCB into a YAML file. Then the tool can be used to apply the footprint positions in the YAML file to the footprints in traced-PCB.

It may be that what you want is to extract the traces/vias from the traced-PCB and import them to the ergogen-PCB, in which case kicad_component_layout is useless.

**Comment by chrishoage** [comment]
Thanks, that actually looks promising, and at the very least is instructive with how to read and write to a kicad_pcb file.

Feel free to close this issue if you like, as mentioned, just figured I'd open it just in case.

**Comment by devbisme** [comment]
I'm actually surprised that so many people are designing keyboards that specialized tools are being built. Good luck with it!
